name: slateos
description: A bespoke, touch-first Linux distro for power users.
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 41

platforms:
  - linux/amd64
  - linux/arm64

modules:
  - type: rpm-ostree
    install:
      - gnome-tweaks
      - distrobox

  # THIS SECTION WAS THE PROBLEM. HERE IS THE FIX:
  - type: default-flatpaks
    notify: true
    configurations:
      - install:
          - org.gnome.TextEditor
          - com.github.tchx84.Flatseal

  - type: gnome-extensions
    install:
      - Dash to Dock
      - Just Perfection
      - Gesture Improvements
