name: slateos
description: A bespoke, touch-first Linux distro for power users.
base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest

platforms:
  - linux/amd64
  - linux/arm64

modules:
  - type: rpm-ostree
    install:
      - gnome-tweaks
      - distrobox

  - type: default-flatpaks
    configurations:
      - notify: true
        install:
          - org.gnome.TextEditor
          - com.github.tchx84.Flatseal

  - type: gnome-extensions
    install:
      - Dash to Dock
      - Just Perfection
      - Tiling Assistant
      - Blur my Shell
      #      - Gesture Improvements
  - type: files
    files:
      - source: system
        destination: /
