# recipes/recipe.yml
name: slateos
description: A bespoke, touch-first Linux distro for power users.
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 41 # Latest stable Fedora

modules:
  - type: rpm-ostree
    install:
      - gnome-extensions-app
      - gnome-tweaks
      - waydroid # For Android app support
      - distrobox # The "Hidden Power" CLI tool

  - type: default-flatpaks
    notify: true
    install:
      - org.gnome.TextEditor
      - com.github.tchx84.Flatseal # To manage app permissions

  - type: gnome-extensions
    install:
      - dash-to-dock@micxgx.gmail.com # iPad-style dock
      - just-perfection-desktop@just-perfection # Clean up UI
      - gesture-improvements@gestures # Enhanced touch swipes
